import pandas as pd

def function1():
    df = pd.read_csv('./Salaries .csv')
    print(df)
    print(f"columns = {df.columns}")
    print(f"shape = {df.shape}")
    print('-' * 80)
    print(df.head(5))
    print('-' * 80)
    print(df.head(10))
    print('-' * 80)
    print(df.tail(5))
    print('-' * 80)
    print(df.tail(10))
    print('-' * 80)
    print(df.columns)
    print('-' * 80)
    print(df.shape)
    print('-' * 80)
    print(df.describe())
    print('-' * 80)
    df.info()
    print('-' * 80)
    # rank_mode = df['rank'].mode()
    # print("rank Column")
    # print(f"Mode = {rank_mode}")
    #
    # discipline_mode = df['discipline'].mode()
    # print("discipline Column")
    # print(f"Mode = {discipline_mode}")
    #
    print('-' * 80)
    phd_max = df['phd'].max()
    phd_min = df['phd'].min()
    phd_mean = df['phd'].mean()
    phd_median = df['phd'].median()
    phd_sd = df['phd'].std()
    print("phd Column :-")
    print(f"Max = {phd_max}, Min = {phd_min}, Mean = {phd_mean}, Median = {phd_median}, SD = {phd_sd}")
    print('. ' * 80)
    service_max = df['service'].max()
    service_min = df['service'].min()
    service_mean = df['service'].mean()
    service_median = df['service'].median()
    service_sd = df['service'].std()
    print("service Column :-")
    print(f"Max = {service_max}, Min = {service_min}, Mean = {service_mean}, Median = {service_median}, SD = {service_sd}")
    print('. ' * 80)
    salary_max = df['salary'].max()
    salary_min = df['salary'].min()
    salary_mean = df['salary'].mean()
    salary_median = df['salary'].median()
    salary_sd = df['salary'].std()
    print("salary Column :-")
    print(f"Max = {salary_max}, Min = {salary_min}, Mean = {salary_mean}, Median = {salary_median}, SD = {salary_sd}")
    print('-' * 80)
    print(df.isna())
    print('-' * 80)
    print(df.isna().sum())
    print('-' * 80)
    rank_mode = df['rank'].mode()
    df['rank'].fillna(rank_mode, inplace=True)
    discipline_mode = df['discipline'].mode()
    df['discipline'].fillna(discipline_mode, inplace=True)
    phd_mean = df['phd'].mean()
    df['phd'].fillna(phd_mean, inplace=True)
    service_mean = df['service'].mean()
    df['service'].fillna(service_mean, inplace=True)
    sex_mode = df['sex'].mode()
    df['sex'].fillna(sex_mode, inplace=True)
    salary_mean = df['salary'].mean()
    df['salary'].fillna(salary_mean, inplace=True)
function1()

